options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # El nombre de conexión ahora usa $PROJECT_ID para usar siempre
  # el ID del proyecto correcto donde se ejecuta la compilación.
  _INSTANCE_CONNECTION_NAME: '$PROJECT_ID:us-central1:controldeobranexus'
  _DB_USER: 'app_user'
  _DB_NAME: 'controldeobranexus'
  _USE_PRIVATE_IP: 'true'
  # Este es el nombre del secreto que tienes en Google Secret Manager
  _DB_PASS_SECRET_NAME: 'APP_DB_PASSWORD'

steps:
  # 1) Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:latest'
      - '-f'
      - 'Administracion/backend/Dockerfile'
      - 'Administracion/backend'

  # 2) Publicar la imagen con la etiqueta de SHA corto
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA']

  # 3) Publicar la imagen con la etiqueta 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:latest']

  # 4) Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'appcontrolarmenia'
      - '--image=gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
      # Asegúrate de que esta es la región correcta de tu Cloud SQL
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60s'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
      # La forma correcta y segura de pasar secretos a Cloud Run
      - '--set-secrets=DB_PASS=${_DB_PASS_SECRET_NAME}:latest'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},USE_PRIVATE_IP=${_USE_PRIVATE_IP}'

images:
  - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:latest'

timeout: '1800s'
