steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:latest'
      - '-f'
      - 'Administracion/backend/Dockerfile'
      - 'Administracion/backend'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'appcontrolarmenia'
      - '--image=gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},USE_PRIVATE_IP=false'

images:
  - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/appcontrolarmenia-backend:latest'

timeout: '1800s'

substitutions:
  _INSTANCE_CONNECTION_NAME: 'your-project:europe-west1:postgresql-instance'
  _DB_USER: 'postgres'
  _DB_PASS: 'your-password'
  _DB_NAME: 'fichajes_db'
